### ISSUE TITLE
Minimal Tasks Checklist for RPG

### ISSUE THREAD

**Issue by raysan5** [alexgesti/Odd-Space#1]
Following task should be completed for the project, please, add comments below if desired and reference big commits to this issue.
 
DESIGN (Wiki)
 - [x] GDD: Game Design Document (`Research: Game Pillars, Quest and Missions, ...`)
 - [x] TDD: Tech Design Document (`Research: Tech Design Document`)
 - [x] GUI Document (`Research: RPG UI Menus`)
 - [x] Art Bible (`Research: Art Bible`)
 - [x] Audio Bible (`Research: Audio Bible`)
 - [x] QA Workflow (`Research: QA Workflow`)
 - [x] Production Plan (`Research: Production Plan`)
 
GENERAL
 - [x] Game resolution: 1280x720px@60fps, support for windowed mode and fullscreen
 - [x] GOD mode (F10): no-damage, fly-around mode, show bounds, visual debug information...
 - [x] Screens and battle transitions (`Research: Camera Battle Transitions`)
 - [x] Turn-based battle system (`Research: RPG Turn-based Combat`)
 - [x] UI: All controls must support multiple states: NORMAL, HOVER/SELECTED, PRESSED, DISABLED
 - [x] UI: All controls and menus must be animated (`Research: Easing and Splines for UI Animations`)
 
BUILD
 - [x] GitHub Actions automated builds (`Research: Automated builds CI + CD`)
 - [x] Assets/Resources loaded from one or multiple ZIP files (`Research: Assets ZIP Management`)
 - [x] Game installer with custom game icon, executable properties (metadata) (`Research: Installer Creation`)
 
SCREEN: LOGO
 - [x] Team logo: custom art, avoid plain text
 - [x] ANIM: Animated logo in/out (`Research: Easing and Splines for UI Animations`)
 - [x] AUDIO: Sound FX characteristic for the logo
 
SCREEN: TITLE
 - [x] Game title, custom art, avoid plain text
 - [x] Game SAVE/LOAD state to/from external file
 - [x] ANIM: Title animation with easings (fading, movement…)
 - [x] AUDIO: Sound FX characteristic for the title appearing
 - [x] AUDIO: Music track specific for the screen
 - [x] UI: Main game menu (custom font): START - CONTINUE - OPTIONS - EXIT
 - [x] UI: ANIM: Animated menu, responsive, visual feedback… (`Research: Easing and Splines for UI Animations`)
 - [x] UI: AUDIO: Buttons/controls fx feedback sounds
 
SCREEN: OPTIONS
 - [x] UI: Basic game config options implemented with custom font
 - [x] UI: OPTION: GRAPHICS: Full Screen mode selection
 - [x] UI: OPTION: GRAPHICS: VSync enabled
 - [x] UI: OPTION: AUDIO: Music volume slider
 - [x] UI: OPTION: AUDIO: Fx sounds volume slider
 - [x] UI: OPTION: CONTROLS: Gamepad configuration
 - [x] ANIM: Animated options menu, responsive, visual feedback...
 - [x] AUDIO: Sound feedback for buttons and sliders
 - [x] AUDIO: Music track specific for the screen
 
 
SCREEN: GAMEPLAY
 - [x] Implement a TOWN map with at least 3 locations to visit (i.e. House, Tavern, Graveyard...)
 - [x] Implement a DUNGEON map with at least 3 map-puzzles to solve (i.e. Activate level, Move rock, Push button…)
 - [x] Implement at least **6 Types of Items** to collect (i.e. Keys, Fruits, Mana, Magic Orb...)
 - [x] Implement at least **2 Playable Characters**, available as the base Team Party
 - [x] Implement at least **3 NPC Characters** (town people, wizard, tavern…)
 - [x] Implement at least **4 Dialogs** with branching with NPC characters (`Research: Dialog System`)
 - [x] Implement at least **3 Quests** (i.e. speak with some NPC, kill some enemy, find some Item)  (`Research: Quests and Missions`)
 - [x] INPUTS: Keyboard/Gamepad inputs supported
 - [x] UI: PAUSE menu available on pause
 - [ ] UI: PAUSE menu animated with feedback (custom font)
 - [ ] AUDIO: PAUSE menu in/out animation with audio feedback
 - [ ] UI: ANIM: Interface elements should be animated with visual feedback
 - [ ] UI: AUDIO: Sound feedback for the interface elements (when required)
 - [x] AUDIO: Minimum of 10 fx game sounds implemented
 - [x] AUDIO: Music track specific for the screen
 - [x] AUDIO: Music effects fade-in/fade-out, lower volume on PAUSE
 
SCREEN: STATS MENU
 - [x] UI: Implement a minimal menu system: **Characters Stats**, **Inventory Items** (`Research: RPG UI Menus, RPG Progression`)
 - [ ] UI: Allow basic Items selection and USE (HP/MP items)
 - [ ] ANIM: Animated stats menu, responsive, visual feedback...
 - [ ] AUDIO: Sound feedback for buttons and other controls
 
SCREEN: BATTLE
 - [x] Implement at least **3 Types of Enemies** (or Boss) with different stats (`Research: RPG Enemies AI`)
 - [x] Implement turn-based combat system, players and enemies should alternate attacks (`Research: RPG Turn-based Combat`)
 - [x] UI: Implement a minimal menu to choose next player actions. (`Research: RPG UI Menus`)
 - [ ] FX: Implement at least **5 Particle Systems** (`Research: Particle System`)
 - [ ] ANIM: Animated battle menu, responsive, visual feedback...
 - [x] AUDIO: Sound feedback for menus controls
 - [x] AUDIO: Minimum of 10 fx player/enemies sounds implemented
 - [x] AUDIO: Music track specific for the screen
 
SCREEN: ENDING
 - [x] Custom background with victory/lose messages (custom font)
 - [ ] UI: Minimal menu to CONTINUE or RETURN to TITLE
 - [ ] ANIM: In/out animations (easings) for ending messages
 - [ ] AUDIO: Sounds for messages and animations
 - [x] AUDIO: Music track specific for the screen
 
**RECOMMENDATION: Keep it simple, focus on the minimum requirements.**
 
*NOTE: This checklist could change at any given point with added/deleted requirements.*
